# Generated by Django 4.2.7 on 2023-12-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emplyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emply',
            name='salary',
            field=models.IntegerField(default=1000),
        ),
    ]
