# Generated by Django 4.2.7 on 2023-12-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emplyapp', '0002_emply_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emply',
            name='department',
            field=models.CharField(max_length=50),
        ),
    ]
