# Generated by Django 4.2.7 on 2023-12-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emplyapp', '0003_alter_emply_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emply',
            name='department',
            field=models.CharField(max_length=100),
        ),
    ]
