# Generated by Django 4.2.7 on 2023-12-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emplyapp', '0004_alter_emply_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='emply',
            name='email',
            field=models.CharField(default='test@gmail.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='emply',
            name='department',
            field=models.CharField(max_length=50),
        ),
    ]
