# Generated by Django 4.1.3 on 2024-01-01 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emplyapp', '0005_emply_email_alter_emply_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emply',
            name='is_Admin',
        ),
    ]
