# Generated by Django 4.1.3 on 2024-01-02 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emplyapp', '0006_remove_emply_is_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
