# Generated by Django 4.1.3 on 2024-01-02 17:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emplyapp', '0007_delete_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromDate', models.DateField(default=datetime.date(2023, 1, 1))),
                ('toDate', models.DateField(default=datetime.date(2023, 1, 1))),
                ('typeOfLeave', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=100)),
                ('leaveStatus', models.CharField(max_length=100)),
            ],
        ),
    ]
