# Generated by Django 4.1.3 on 2024-01-03 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emplyapp', '0008_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='user',
            field=models.CharField(default='', max_length=255),
        ),
    ]
