# Generated by Django 4.1.3 on 2024-01-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emplyapp', '0009_leave_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='emply',
            name='empId',
            field=models.IntegerField(default=1000),
        ),
    ]
