# Generated by Django 4.1.3 on 2024-02-05 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emplyapp', '0010_emply_empid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emply',
            name='dob',
        ),
    ]
